### ISSUE TITLE
Preview text file argument?

### ISSUE THREAD

**Issue by mxmilkiib** [xlucn/fontpreview-ueberzug#21]
It would be nice to have a block of code loaded, but it's a bit difficult to make that into a commandline argument. How about a flag to specify a file to read the preview text string from?

**Comment by 2084x** [comment]
`-t "$(cat my.file)"` is difficult?

**Comment by xlucn** [comment]
> `-t "$(cat my.file)"` is difficult?

That should be enough. @mxmilkiib would that work for you?

**Comment by mxmilkiib** [comment]
Very fair point, thanks :)
